#pragma once
//가중치
enum {
	LEVEL_WEIGHT_SCARECROW = 10,
	LEVEL_WEIGHT_GOBLIN = 10,
	LEVEL_WEIGHT_ORC = 50,
	LEVEL_WEIGHT_DEMON = 1000
};
//최소 스탯
enum {
	STAT_MIN_SCARECROW = 10,
	STAT_MIN_GOBLIN = 30,
	STAT_MIN_ORC = 100,
	STAT_MIN_DEMON = 500,

	//보스
	STAT_MIN_GOBLINKING = 60,
	STAT_MIN_ORCKING = 200,
	STAT_MIN_DEMONKING = 1000
};

//경험치
enum {
	EXP_SCARECROW = 50,
	EXP_GOBLIN = 150,
	EXP_ORC = 300,
	EXP_DEMON = 1500,

	//보스
	EXP_GOBLINKING = 300,
	EXP_ORCKING = 600,
	EXP_DEMONKING = 5000
};
//골드
enum {
	GOLD_SCARECROW = 10,
	GOLD_GOBLIN = 50,
	GOLD_ORC = 70,
	GOLD_DEMON = 300,
	//보스
	GOLD_GOBLINKING = 100,
	GOLD_ORCKING = 150,
	GOLD_DEMONKING = 500
};
//아이템 드랍 확률
enum {
	ITEM_SCARECROW = 5,
	ITEM_GOBLIN = 10,
	ITEM_ORC = 20,
	ITEM_DEMON = 50,
	//보스
	ITEM_GOBLINKING = 30,
	ITEM_ORCKING = 50,
	ITEM_DEMONKING = 100
};
//boss ATK
enum {
	ATK_GOBLINKING = 30,
	ATK_ORCKING = 50,
	ATK_DEMONKING = 200
};

//각 몬스터 등장 수
enum {
	NUM_SCARECROW = 10,
	NUM_GOBLIN = 10,
	NUM_ORC = 10,
	NUM_DEMON = 10
};